/**
 * Mock LLM Provider — returns stable Chinese explanations, no network.
 * @module mock-llm-provider
 * @previewOnly
 */

import type { LlmChatMessage, LlmChatRequest, LlmProvider } from "./llm-provider-contract.ts";
import { LlmProviderMode } from "./llm-provider-contract.ts";
import { createMockSuccessResult, createSafeError, createSafeResult } from "./llm-safe-result.ts";

export class MockLlmProvider implements LlmProvider {
  readonly mode = LlmProviderMode.Mock;
  readonly label = "Mock LLM Provider (dev preview)";

  async generate(request: LlmChatRequest): Promise<ReturnType<LlmProvider["generate"]>> {
    const validationError = validateRequest(request);
    if (validationError) {
      return createSafeResult({
        answerSummary: "[mock validation blocked] " + validationError,
        providerMode: "mock",
        realProviderCalled: false,
        networkAccessed: false,
        warnings: ["Request failed mock provider validation. No external service was called."],
        error: createSafeError({ kind: "invalid_request", message: validationError, retryable: false }),
      });
    }

    const userMessages = request.messages.filter(function (m) { return m.role === "user"; });
    const lastUserMessage = userMessages[userMessages.length - 1];
    const question = lastUserMessage ? lastUserMessage.content : "";

    const answer = generateMockAnswer(question, request);
    return createMockSuccessResult(answer);
  }
}

export var mockLlmProvider = new MockLlmProvider();

function validateRequest(request: LlmChatRequest): string | null {
  if (!Array.isArray(request.messages) || request.messages.length === 0) {
    return "Message list cannot be empty.";
  }
  var userMessages = request.messages.filter(function (m) { return m.role === "user"; });
  if (userMessages.length === 0) {
    return "Request must contain at least one user message.";
  }
  var lastContent = userMessages[userMessages.length - 1].content;
  if (!lastContent || lastContent.trim().length === 0) {
    return "Question cannot be empty.";
  }
  for (var i = 0; i < request.messages.length; i++) {
    if (containsSensitiveContent(request.messages[i].content)) {
      return "Message contains sensitive fields (token/secret/api_key etc.), rejected.";
    }
  }
  if (request.maxInputChars && request.maxInputChars > 0) {
    var totalChars = request.messages.reduce(function (sum, m) { return sum + m.content.length; }, 0);
    if (totalChars > request.maxInputChars) {
      return "Total input chars (" + totalChars + ") exceeds limit (" + request.maxInputChars + ").";
    }
  }
  return null;
}

var SENSITIVE_PATTERNS = [
  /\btoken\b/i,
  /\bsecret\b/i,
  /\bpassword\b/i,
  /\bapi[_\s-]*key\b/i,
  /\bDATABASE_URL\b/i,
  /\bcookie\b/i,
  /\bauthorization\b/i,
  /\bbearer\s+\S+/i,
  /\bXFYUN_SPARK_API_(KEY|SECRET|TOKEN)\b/i,
  /\bprivate[_\s-]*key\b/i,
];

function containsSensitiveContent(text: string): boolean {
  return SENSITIVE_PATTERNS.some(function (p) { return p.test(text); });
}

function generateMockAnswer(question: string, _request: LlmChatRequest): string {
  var normalized = question.trim().toLowerCase();
  var topic = detectMockTopic(normalized);
  var lines: string[] = [];

  lines.push("[Mock Provider] dev preview");
  lines.push("");
  lines.push("This answer was generated by the mock provider. No real AI model was called, no network was accessed.");
  lines.push("");

  if (topic === "code") {
    lines.push("You asked about code/programming. Mock provider gives a simulated explanation:");
    lines.push("");
    lines.push("Suggestions:");
    lines.push("1. Read the code line by line, understand each function.");
    lines.push("2. Pay attention to variable naming and type annotations.");
    lines.push("3. Try running a minimal reproducible example locally.");
    lines.push("4. If it involves algorithms, try simulating with different inputs.");
    lines.push("");
  } else if (topic === "concept") {
    lines.push("You asked about a concept/theory. Mock provider gives a simulated explanation:");
    lines.push("");
    lines.push("Suggestions:");
    lines.push("1. Restate the concept's original definition in your own words.");
    lines.push("2. Find related code examples in this chapter for comparison.");
    lines.push("3. Think about how this concept applies to your actual projects.");
    lines.push("4. Consult relevant documentation or references for deeper understanding.");
    lines.push("");
  } else if (topic === "explain") {
    lines.push("You want something explained. Mock provider simulates:");
    lines.push("");
    lines.push("Suggestions:");
    lines.push("1. Review the main goals and problems this chapter solves.");
    lines.push("2. Pay attention to the context (surrounding paragraphs).");
    lines.push("3. Identify key patterns in the code (design patterns, idioms etc.).");
    lines.push("4. Try to re-express this content in your own words.");
    lines.push("");
  } else {
    lines.push("You asked a question. Mock provider gives a simulated answer:");
    lines.push("");
    lines.push("Since this uses mock provider (dev preview mode), this response is");
    lines.push("generated by fixed rules and does not contain real AI analysis.");
    lines.push("");
    lines.push("In dev environment, you can enable real external provider by setting");
    lines.push("LAP_LLM_DEV_PROVIDER_ENABLED=true and configuring LAP_LLM_DEV_* env vars.");
    lines.push("");
    lines.push("Mock provider suggestion: break the question into smaller sub-questions,");
    lines.push("and analyze specific code blocks or paragraphs from this chapter step by step.");
    lines.push("");
  }

  var truncated = question.slice(0, 200);
  if (question.length > 200) truncated += "...";
  lines.push("Original question: \"" + truncated + "\"");
  lines.push("");
  lines.push("[Disclaimer]");
  lines.push("- Provider: mock (default)");
  lines.push("- realProviderCalled: false");
  lines.push("- networkAccessed: false");
  lines.push("- secretSafe: true");
  lines.push("- Raw prompt/response will not be saved");
  lines.push("- Tools/Agent will not be executed");
  lines.push("- devOnly: true, productionReady: false");
  lines.push("- dev preview - not connected to production AI service");

  return lines.join("\n");
}

type MockTopic = "code" | "concept" | "explain" | "general";

function detectMockTopic(question: string): MockTopic {
  var codeKeywords = [
    "code", "function", "class", "variable", "syntax", "bug", "error", "compile",
    "import", "export", "return", "async", "await", "promise",
  ];
  var conceptKeywords = [
    "concept", "theory", "design", "architecture", "pattern", "what is",
    "definition", "difference", "relationship",
  ];
  var explainKeywords = [
    "explain", "why", "reason", "understand", "meaning",
  ];

  var codeScore = countKeywords(question, codeKeywords);
  var conceptScore = countKeywords(question, conceptKeywords);
  var explainScore = countKeywords(question, explainKeywords);

  if (codeScore >= conceptScore && codeScore >= explainScore && codeScore > 0) return "code";
  if (conceptScore >= explainScore && conceptScore > 0) return "concept";
  if (explainScore > 0) return "explain";
  return "general";
}

function countKeywords(text: string, keywords: string[]): number {
  var count = 0;
  for (var i = 0; i < keywords.length; i++) {
    if (text.indexOf(keywords[i]) !== -1) count++;
  }
  return count;
}
