import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
var D = import.meta.dirname;
var LD = join(D, "auth", "login");
function rf(p) { return readFileSync(join(LD, p), "utf8"); }
var a = rf("actions.ts");
test("guard before DB", function() { var gi=a.indexOf("getDevLoginGuardStatus"); var di=a.indexOf("isDbAvailable"); assert.ok(gi>=0&&di>=0&&gi<di); });
test("guard safe check", function() { assert.ok(a.includes("loginGuardStatusIsSafe")); });
test("guard enabled", function() { assert.ok(a.includes("guard.enabled")); });
test("blocked msg", function() { assert.ok(a.includes("登录功能未启用")); });
test("user empty", function() { assert.ok(a.includes("empty")||a.includes("required")||a.includes("不能为空")); });
test("pw empty", function() { assert.ok(a.includes("password")&&(a.includes("empty")||a.includes("不能为空"))); });
test("user maxlen", function() { assert.ok(a.includes("USERNAME_MAX_LENGTH")); });
test("pw maxlen", function() { assert.ok(a.includes("PASSWORD_MAX_LENGTH")); });
test("trim", function() { assert.ok(a.includes("trim()")); });
test("db check", function() { assert.ok(a.includes("isDbAvailable")); });
test("db err safe", function() { assert.ok(a.includes("unavailable")||a.includes("暂时不可用")); });
test("getUserByUsername", function() { assert.ok(a.includes("getUserByUsername")); });
test("PrismaUserRepo", function() { assert.ok(a.includes("PrismaUserRepository")); });
test("verifyPassword", function() { assert.ok(a.includes("verifyPassword")); });
test("pwHash", function() { assert.ok(a.includes("passwordHash")); });
test("same error x3", function() { var ls=a.split("\n"); var c=0; for(var i=0;i<ls.length;i++){if(ls[i].includes("用户名或密码错误"))c++;} assert.ok(c>=2,"got "+c); });
test("no user leak", function() { assert.ok(!a.includes('reason: "用户不存在"')); assert.ok(!a.includes("reason: 'user not found'")); });
test("user.id", function() { assert.ok(a.includes("user.id")); });
test("user.username", function() { assert.ok(a.includes("user.username")); });
test("devOnly", function() { assert.ok(a.includes("devOnly: true")); });
test("sessionCreated", function() { assert.ok(a.includes("sessionCreated: true")); });
test("createDevSession", function() { assert.ok(a.includes("createDevSessionData")); });
test("serialize", function() { assert.ok(a.includes("serializeDevSession")); });
test("cookie name", function() { assert.ok(a.includes("DEV_SESSION_COOKIE_NAME")); });
test("httpOnly", function() { assert.ok(a.includes("httpOnly")); });
test("safe error", function() { assert.ok(a.includes("try again")||a.includes("稍后再试")); });
test("errorCategory", function() { assert.ok(a.includes("errorCategory")); });
test("no OAuth2", function() { assert.ok(!a.includes("OAuth2")&&!a.includes("authorization_code")); });
test("no email verify", function() { assert.ok(!a.includes("verifyEmail")&&!a.includes("email_verified")); });
test("no pw reset", function() { assert.ok(!a.includes("resetPassword")&&!a.includes("forgot")); });
test("guard < user lookup", function() { var gi=a.indexOf("if (!guard.enabled)"); var ui=a.indexOf("getUserByUsername"); assert.ok(gi>=0&&ui>=0&&gi<ui); });
test("guard < session", function() { var gi=a.indexOf("if (!guard.enabled)"); var fi=a.indexOf("createDevSessionData"); var si=a.indexOf("createDevSessionData",fi+1); assert.ok(gi>=0&&si>=0&&gi<si); });
