import type { DbPackageStatus } from "./types.js";

// Load Prisma Client typing shim for models not yet generated.
// Remove this import after running `npx prisma generate`.
import "./generated-prisma-shim.js";

export type {
  AbilityProfileRecord,
  AddFavoriteArticleInput,
  BookChapterRecord,
  BookFavoriteRecord,
  BookListItem,
  BookReaderData,
  BookRecord,
  BookRepository,
  BookSourceType,
  ArticleFavoriteRecord,
  ArticleReadingRecord,
  ArticleRepository,
  AddFavoriteBookInput,
  AddProblemFavoriteInput,
  GetProblemPracticeStatusInput,
  IsFavoriteArticleInput,
  IsProblemFavoriteInput,
  ListArticleReadingsByOwnerInput,
  ListFavoriteArticlesByOwnerInput,
  ListProblemFavoritesByOwnerInput,
  RemoveFavoriteArticleInput,
  RemoveProblemFavoriteInput,
  ProblemFavoriteRecord,
  ProblemFavoriteRepository,
  ProblemPracticeActivityRecord,
  ProblemPracticeRepository,
  ProblemPracticeStatus,
  RecordArticleReadingInput,
  RecordProblemPracticeInput,
  ListProblemPracticeByOwnerInput,
  RemoveProblemPracticeInput,
  // A390: Reader bookmark/note types
  ReaderBookmarkRecord,
  ReaderNoteRecord,
  ReaderBookmarkRepository,
  ReaderNoteRepository,
  AddReaderBookmarkInput,
  RemoveReaderBookmarkInput,
  ListReaderBookmarksByOwnerInput,
  IsReaderBookmarkedInput,
  AddReaderNoteInput,
  UpdateReaderNoteInput,
  RemoveReaderNoteInput,
  ListReaderNotesByOwnerInput,
  ListReaderNotesByBookChapterInput,
  // A392: LearningActivity / ReadingSession types
  LearningActivityType,
  LearningActivityTargetType,
  LearningActivityRecord,
  RecordLearningActivityInput,
  ListLearningActivitiesByOwnerInput,
  LearningActivityRepository,
  ReadingSessionRecord,
  StartReadingSessionInput,
  EndReadingSessionInput,
  ListReadingSessionsByOwnerInput,
  ReadingSessionSummary,
  ReadingSessionRepository,
  // A395: ProblemWrongBook types
  ProblemWrongBookReviewStatus,
  ProblemWrongBookRecord,
  ProblemWrongBookRepository,
  AddProblemWrongBookInput,
  RecordProblemWrongInput,
  RemoveProblemWrongBookInput,
  UpdateProblemWrongBookReviewStatusInput,
  UpdateProblemWrongBookNoteInput,
  ListProblemWrongBookByOwnerInput,
  IsProblemInWrongBookInput,
  VALID_WRONG_BOOK_REVIEW_STATUSES,
  // A400: DailyChallengeProgress types
  DailyChallengeProgressRepository,
  DailyChallengeProgressRecord,
  DailyChallengeProgressUpsertInput,
  DailyChallengeProgressUpsertResult,
  DailyChallengeProgressFindResult,
  DailyChallengeProgressClearResult,
  DailyChallengeProgressSafetyMetadata,
  DailyChallengeProgressStatus,
  ChapterQaFeedbackRating,
  ChapterQaFeedbackRecord,
  ChapterQaFeedbackRepository,
  ChapterQaHistoryAnswerMetadataInput,
  ChapterQaHistoryAnswerSource,
  ChapterQaHistoryFallbackReason,
  ChapterQaHistoryProviderErrorCategory,
  ChapterQaHistoryProviderMode,
  ChapterQaHistoryRecord,
  ChapterQaHistoryRepository,
  ClearChapterQaFeedbackInput,
  ContentChunkRecord,
  CreateChapterQaHistoryRecordInput,
  CreateDailyRecommendationItemInput,
  CreateDailyRecommendationsInput,
  CreateBookChapterInput,
  CreateBookWithContentInput,
  CreateBookWithContentResult,
  CreateContentChunkInput,
  CreateProblemInput,
  CreateUserInput,
  DatabaseEnvStatus,
  DatabaseProvider,
  DailyRecommendationRecord,
  DeleteBookInput,
  DeleteBookResult,
  DbPackageStatus,
  FavoriteRepository,
  FindUserInput,
  GetChapterQaFeedbackInput,
  GetDailyRecommendationsInput,
  GetChapterQaHistoryRecordByIdInput,
  GetReadingProgressInput,
  IsFavoriteBookInput,
  LearningRepository,
  ListBooksInput,
  ListChapterQaHistoryRecordsInput,
  ListFavoritesByOwnerInput,
  ListProblemsInput,
  ListReadingProgressInput,
  MarkChapterCompletedInput,
  AddMemoryInput,
  DeleteMemoryInput,
  ListMemoriesByOwnerInput,
  MemoryRecord,
  MemoryRecordCategory,
  MemoryRecordSource,
  MemoryRepository,
  ProblemDifficulty,
  ProblemRecord,
  ReadingProgressRecord,
  ReadingProgressRepository,
  PrismaClient,
  RecommendationStatus,
  RemoveFavoriteBookInput,
  UpsertAbilityProfileInput,
  UpsertChapterQaFeedbackInput,
  UpdateUserInput,
  UpdateBookMetadataInput,
  UpdateBookMetadataResult,
  UpsertReadingProgressInput,
  UserRecord,
  UserRepository,
} from "./types.js";
export { Prisma } from "./types.js";
export {
  AgentLlmCallPersistence,
  persistMockLlmCallPreview,
} from "./agent-llm-call-persistence.js";
export {
  createRuntimeMockLlmPersistenceMetadataSummary,
  createRuntimeMockLlmSafeErrorSummary,
  detectRuntimeMockLlmPersistenceSafetyIssues,
  mapRuntimeLlmCallResultToMockLlmPersistenceInput,
  persistRuntimeMockLlmCallPreview,
  PrismaRuntimeMockLlmCallPersistence,
} from "./runtime-mock-llm-call-persistence.js";
export {
  createRuntimeControlledSparkDiagnosticPersistenceMetadataSummary,
  createRuntimeControlledSparkDiagnosticSafeErrorSummary,
  detectRuntimeControlledSparkDiagnosticPersistenceSafetyIssues,
  mapControlledSparkDiagnosticResultToSparkPersistenceInput,
  persistRuntimeControlledSparkDiagnosticPreview,
  PrismaRuntimeControlledSparkDiagnosticPersistence,
  RuntimeControlledSparkDiagnosticPersistenceSafetyIssue,
} from "./runtime-controlled-spark-diagnostic-persistence.js";
export {
  AgentToolSandboxAuditPersistence,
  persistReadOnlyToolSandboxAuditPreview,
} from "./agent-tool-sandbox-audit-persistence.js";
export {
  createSparkDiagnosticPersistenceMetadataSummary,
  createSparkDiagnosticSafeErrorSummary,
  detectSparkDiagnosticSafetyIssues,
  mapSparkDiagnosticStatusToRuntimeLlmCallStatus,
  persistSparkDiagnosticPreview,
  PrismaSparkDiagnosticPersistence,
  SparkDiagnosticPersistenceSafetyIssue,
} from "./spark-diagnostic-persistence.js";
export {
  PrismaAgentRuntimeMockRunnerPreview,
} from "./agent-runtime-mock-runner-preview.js";
export {
  createPrismaClient,
  disconnectPrismaClient,
  getPrismaClient,
} from "./client.js";
export type { PrismaClientOptions } from "./client.js";
export {
  assertDatabaseUrl,
  getDatabaseEnvStatus,
  getDatabaseUrl,
  hasDatabaseUrl,
} from "./env.js";
export {
  mapAgentPermissionDecisionPreviewToCreateInput,
  mapAgentPermissionRequestPreviewToCreateInput,
  mapAgentRuntimeAuditEventPreviewToAppendRuntimeAuditLogInput,
  mapAgentRuntimeErrorsToExecutionErrorsJson,
  mapAgentRuntimeEventPreviewToAppendRuntimeEventInput,
  mapAgentRuntimeLlmCallPreviewToAppendRuntimeLlmCallInput,
  mapAgentRuntimePreviewToCreateRuntimeExecutionInput,
  mapAgentRuntimePreviewToRuntimePersistenceInputs,
  mapAgentRuntimeStepPreviewToAppendRuntimeStepInput,
  mapAgentRuntimeToolCallPreviewToAppendRuntimeToolCallInput,
  mapAgentTaskEventPreviewToAppendInput,
  mapAgentTaskRecordPreviewToCreateInput,
  mapAgentTaskSnapshotPreviewToAppendInput,
} from "./mappers/index.js";
export {
  createAbilityProfileInputFromScoringResult,
  createBookRepositoryInputFromImportedBook,
  createCompletedChapterProgress,
  createDailyRecommendationsInputFromRecommendationResult,
  createProblemInputFromRecommendationProblem,
  createReadingProgressUpdateFromReaderState,
  mapProblemAttemptsToLearningEvents,
  mapProblemAttemptToLearningEvent,
  mapImportedBookSourceType,
  PrismaAgentPermissionRepository,
  PrismaAgentRuntimeRepository,
  PrismaAgentTaskRepository,
  PrismaArticleRepository,
  PrismaBookRepository,
  PrismaChapterQaFeedbackRepository,
  PrismaChapterQaHistoryRepository,
  PrismaFavoriteRepository,
  PrismaLearningRepository,
  PrismaLearningActivityRepository,
  PrismaMemoryRepository,
  PrismaProblemAttemptRepository,
  PrismaProblemFavoriteRepository,
  PrismaProblemPracticeRepository,
  PrismaProblemWrongBookRepository,
  PrismaReaderBookmarkRepository,
  PrismaReaderNoteRepository,
  PrismaReadingProgressRepository,
  PrismaReadingSessionRepository,
  PrismaUserRepository,
  createDailyChallengeProgressRepository,
  getDailyChallengeProgressRepository,
  isDailyChallengeDbGuardActive,
  createRealDailyChallengeProgressRepository,
  normalizeProgressRatio,
} from "./repositories/index.js";
export {
  createReadingProgressPrismaRepositoryAdapter,
} from "./reading-progress-prisma-adapter.js";
export {
  createBlockedReadingProgressDbIntegrationGuardPreview,
  evaluateReadingProgressDbIntegrationGuard,
} from "./reading-progress-db-integration-guard.js";
export type {
  LlmCallPersistenceInput,
  LlmChatCompletionResultLike,
  MockLlmCallPersistenceBlockedReason,
  PersistMockLlmCallPreviewOptions,
  PersistMockLlmCallPreviewResult,
} from "./agent-llm-call-persistence.js";
export type {
  PersistRuntimeMockLlmCallInput,
  PersistRuntimeMockLlmCallOptions,
  PersistRuntimeMockLlmCallResult,
  RuntimeLlmCallExecutorLike,
  RuntimeLlmCallRequestLike,
  RuntimeLlmCallResultLike,
  RuntimeLlmCallSafeErrorSummaryLike,
  RuntimeLlmCallUsageLike,
  RuntimeMockLlmMetadataSummary,
  RuntimeMockLlmPersistenceMetadataSummary,
  RuntimeMockLlmPersistenceSafetyIssue,
  RuntimeMockLlmSafeErrorSummary,
  RuntimeMockLlmSafeErrorSummaryOptions,
} from "./runtime-mock-llm-call-persistence.js";
export type {
  ControlledSparkDiagnosticExecutorLike,
  ControlledSparkDiagnosticRequestLike,
  ControlledSparkDiagnosticResultLike,
  ControlledSparkDiagnosticStatus,
  ControlledSparkDiagnosticUsageLike,
  PersistRuntimeControlledSparkDiagnosticInput,
  PersistRuntimeControlledSparkDiagnosticOptions,
  PersistRuntimeControlledSparkDiagnosticResult,
  RuntimeControlledSparkDiagnosticMetadataSummary,
  RuntimeControlledSparkDiagnosticPersistenceMetadataSummary,
  RuntimeControlledSparkDiagnosticSafeErrorSummary,
  RuntimeControlledSparkDiagnosticSafeErrorSummaryOptions,
} from "./runtime-controlled-spark-diagnostic-persistence.js";
export type {
  PersistReadOnlyToolSandboxAuditPreviewOptions,
  PersistReadOnlyToolSandboxAuditPreviewResult,
  ReadOnlyToolSandboxExecutionResultLike,
  ReadOnlyToolSandboxPersistenceBlockedReason,
  ReadOnlyToolSandboxPersistenceInput,
} from "./agent-tool-sandbox-audit-persistence.js";
export type {
  ReadingProgressPrismaAdapterCapabilities,
  ReadingProgressPrismaAdapterOptions,
  ReadingProgressPrismaAdapterSafetyStatus,
  ReadingProgressPrismaAuditPreview,
  ReadingProgressPrismaBlocker,
  ReadingProgressPrismaDelegateLike,
  ReadingProgressPrismaFindResult,
  ReadingProgressPrismaIdempotencyPreview,
  ReadingProgressPrismaIdentity,
  ReadingProgressPrismaLikeClient,
  ReadingProgressPrismaRecordView,
  ReadingProgressPrismaRepositoryAdapter,
  ReadingProgressPrismaUpsertInput,
  ReadingProgressPrismaUpsertResult,
} from "./reading-progress-prisma-adapter.js";
export type {
  ReadingProgressDbIntegrationGuardBlocker,
  ReadingProgressDbIntegrationGuardInput,
  ReadingProgressDbIntegrationGuardPreview,
  ReadingProgressDbIntegrationGuardStatus,
} from "./reading-progress-db-integration-guard.js";
export type {
  PersistSparkDiagnosticPreviewOptions,
  PersistSparkDiagnosticPreviewResult,
  SparkControlledDiagnosticCallResultLike,
  SparkDiagnosticControlledStatus,
  SparkDiagnosticMetadataSummary,
  SparkDiagnosticPersistenceInput,
  SparkDiagnosticRuntimeLlmCallStatus,
  SparkDiagnosticSafeErrorSummary,
  SparkDiagnosticSafeErrorSummaryOptions,
} from "./spark-diagnostic-persistence.js";
export type {
  MockRuntimePersistenceCounts,
  MockRuntimePreviewPlanLike,
  PersistableMockRuntimePreviewInput,
  PersistMockRuntimePreviewOptions,
  PersistMockRuntimePreviewResult,
} from "./agent-runtime-mock-runner-preview.js";
export type {
  AgentPermissionDecisionPreviewLike,
  AgentPermissionRequestPreviewLike,
  AgentRuntimeAuditEventPreviewLike,
  AgentRuntimeErrorPreviewLike,
  AgentRuntimeEventPreviewLike,
  AgentRuntimeLlmCallPreviewLike,
  AgentRuntimePersistencePreviewInputs,
  AgentRuntimePreviewLike,
  AgentRuntimeStepPreviewLike,
  AgentRuntimeTokenEstimateLike,
  AgentRuntimeToolCallPreviewLike,
  AgentRuntimeTransitionResultLike,
  AgentTaskEventPreviewLike,
  AgentTaskExecutionReadinessPreviewLike,
  AgentTaskRecordPreviewLike,
  AgentTaskSnapshotPreviewLike,
  MapAgentPermissionDecisionPreviewOptions,
  MapAgentPermissionDecisionPreviewToCreateInputOptions,
  MapAgentPermissionRequestPreviewOptions,
  MapAgentPermissionRequestPreviewToCreateInputOptions,
} from "./mappers/index.js";
export type {
  AbilityProfileLike,
  AbilityScoringResultLike,
  AgentPermissionDecisionRecord,
  AgentPermissionRepository,
  AgentPermissionRepositoryJsonValue,
  AgentPermissionRequestRecord,
  AgentRuntimeAuditLogRecord,
  AgentRuntimeEventRecord,
  AgentRuntimeExecutionRecord,
  AgentRuntimeLlmCallRecord,
  AgentRuntimeRepository,
  AgentRuntimeRepositoryJsonValue,
  AgentRuntimeStepRecord,
  AgentRuntimeToolCallRecord,
  AgentTaskEventRecord,
  AgentTaskRecord,
  AgentTaskRepository,
  AgentTaskRepositoryJsonValue,
  AgentTaskSnapshotRecord,
  AgentTaskTimelineOrder,
  AppendAgentTaskEventInput,
  AppendAgentTaskSnapshotInput,
  AppendRuntimeAuditLogPreviewInput,
  AppendRuntimeEventPreviewInput,
  AppendRuntimeLlmCallPreviewInput,
  AppendRuntimeStepPreviewInput,
  AppendRuntimeToolCallPreviewInput,
  CreateAbilityProfileInputFromScoringResultInput,
  CreateAgentPermissionDecisionPreviewInput,
  CreateAgentPermissionRequestPreviewInput,
  CreateAgentTaskInput,
  CreateRuntimeExecutionPreviewInput,
  CreateCompletedChapterProgressInput,
  CreateDailyRecommendationsInputFromRecommendationResultInput,
  CreateProblemAttemptInput,
  CreateReadingProgressUpdateFromReaderStateInput,
  ImportedBookRepositoryChapter,
  ImportedBookRepositoryChunk,
  ImportedBookRepositoryDocument,
  ImportedBookRepositoryInput,
  ImportedBookRepositorySourceType,
  LearningMapperJsonObject,
  LearningMapperJsonPrimitive,
  LearningMapperJsonValue,
  LearningProblemDifficulty,
  LearningRecommendationStatus,
  ListAgentTaskTimelineOptions,
  ListAgentTasksByUserOptions,
  ListAgentPermissionDecisionsByRequestOptions,
  ListAgentPermissionDecisionsByTaskOptions,
  ListAgentPermissionRequestsByTaskOptions,
  ListRecentAgentPermissionRequestPreviewsOptions,
  ListRuntimeExecutionsByTaskOptions,
  ListRuntimeExecutionsByUserOptions,
  ListRuntimeRecordsByExecutionOptions,
  ListRecentPreviewTasksOptions,
  ListProblemAttemptsByUserOptions,
  ProblemAttemptCorrectnessInput,
  ProblemAttemptDifficultyInput,
  ProblemAttemptLearningDifficulty,
  ProblemAttemptLearningEvent,
  ProblemAttemptLearningEventJsonObject,
  ProblemAttemptLearningEventJsonPrimitive,
  ProblemAttemptLearningEventJsonValue,
  ProblemAttemptRecord,
  ProblemAttemptRepository,
  ProblemAttemptStatusInput,
  RecommendationProblemLike,
  RecommendationReasonLike,
  RecommendationResultLike,
  RecommendedProblemLike,
} from "./repositories/index.js";

export const dbPackage = "db";

export const dbPackageStatus: DbPackageStatus = "client-boundary";
