import type { DbPackageStatus } from "./types.js";

export type {
  AbilityProfileRecord,
  BookChapterRecord,
  BookListItem,
  BookReaderData,
  BookRecord,
  BookRepository,
  BookSourceType,
  ChapterQaFeedbackRating,
  ChapterQaFeedbackRecord,
  ChapterQaFeedbackRepository,
  ChapterQaHistoryAnswerMetadataInput,
  ChapterQaHistoryAnswerSource,
  ChapterQaHistoryFallbackReason,
  ChapterQaHistoryProviderErrorCategory,
  ChapterQaHistoryProviderMode,
  ChapterQaHistoryRecord,
  ChapterQaHistoryRepository,
  ClearChapterQaFeedbackInput,
  ContentChunkRecord,
  CreateChapterQaHistoryRecordInput,
  CreateDailyRecommendationItemInput,
  CreateDailyRecommendationsInput,
  CreateBookChapterInput,
  CreateBookWithContentInput,
  CreateBookWithContentResult,
  CreateContentChunkInput,
  CreateProblemInput,
  CreateUserInput,
  DatabaseEnvStatus,
  DatabaseProvider,
  DailyRecommendationRecord,
  DbPackageStatus,
  FindUserInput,
  GetChapterQaFeedbackInput,
  GetDailyRecommendationsInput,
  GetChapterQaHistoryRecordByIdInput,
  GetReadingProgressInput,
  LearningRepository,
  ListBooksInput,
  ListChapterQaHistoryRecordsInput,
  ListProblemsInput,
  ListReadingProgressInput,
  MarkChapterCompletedInput,
  ProblemDifficulty,
  ProblemRecord,
  ReadingProgressRecord,
  ReadingProgressRepository,
  PrismaClient,
  RecommendationStatus,
  UpsertAbilityProfileInput,
  UpsertChapterQaFeedbackInput,
  UpdateUserInput,
  UpsertReadingProgressInput,
  UserRecord,
  UserRepository,
} from "./types.js";
export { Prisma } from "./types.js";
export {
  AgentLlmCallPersistence,
  persistMockLlmCallPreview,
} from "./agent-llm-call-persistence.js";
export {
  createRuntimeMockLlmPersistenceMetadataSummary,
  createRuntimeMockLlmSafeErrorSummary,
  detectRuntimeMockLlmPersistenceSafetyIssues,
  mapRuntimeLlmCallResultToMockLlmPersistenceInput,
  persistRuntimeMockLlmCallPreview,
  PrismaRuntimeMockLlmCallPersistence,
} from "./runtime-mock-llm-call-persistence.js";
export {
  createRuntimeControlledSparkDiagnosticPersistenceMetadataSummary,
  createRuntimeControlledSparkDiagnosticSafeErrorSummary,
  detectRuntimeControlledSparkDiagnosticPersistenceSafetyIssues,
  mapControlledSparkDiagnosticResultToSparkPersistenceInput,
  persistRuntimeControlledSparkDiagnosticPreview,
  PrismaRuntimeControlledSparkDiagnosticPersistence,
  RuntimeControlledSparkDiagnosticPersistenceSafetyIssue,
} from "./runtime-controlled-spark-diagnostic-persistence.js";
export {
  AgentToolSandboxAuditPersistence,
  persistReadOnlyToolSandboxAuditPreview,
} from "./agent-tool-sandbox-audit-persistence.js";
export {
  createSparkDiagnosticPersistenceMetadataSummary,
  createSparkDiagnosticSafeErrorSummary,
  detectSparkDiagnosticSafetyIssues,
  mapSparkDiagnosticStatusToRuntimeLlmCallStatus,
  persistSparkDiagnosticPreview,
  PrismaSparkDiagnosticPersistence,
  SparkDiagnosticPersistenceSafetyIssue,
} from "./spark-diagnostic-persistence.js";
export {
  PrismaAgentRuntimeMockRunnerPreview,
} from "./agent-runtime-mock-runner-preview.js";
export {
  createPrismaClient,
  disconnectPrismaClient,
  getPrismaClient,
} from "./client.js";
export type { PrismaClientOptions } from "./client.js";
export {
  assertDatabaseUrl,
  getDatabaseEnvStatus,
  getDatabaseUrl,
  hasDatabaseUrl,
} from "./env.js";
export {
  mapAgentPermissionDecisionPreviewToCreateInput,
  mapAgentPermissionRequestPreviewToCreateInput,
  mapAgentRuntimeAuditEventPreviewToAppendRuntimeAuditLogInput,
  mapAgentRuntimeErrorsToExecutionErrorsJson,
  mapAgentRuntimeEventPreviewToAppendRuntimeEventInput,
  mapAgentRuntimeLlmCallPreviewToAppendRuntimeLlmCallInput,
  mapAgentRuntimePreviewToCreateRuntimeExecutionInput,
  mapAgentRuntimePreviewToRuntimePersistenceInputs,
  mapAgentRuntimeStepPreviewToAppendRuntimeStepInput,
  mapAgentRuntimeToolCallPreviewToAppendRuntimeToolCallInput,
  mapAgentTaskEventPreviewToAppendInput,
  mapAgentTaskRecordPreviewToCreateInput,
  mapAgentTaskSnapshotPreviewToAppendInput,
} from "./mappers/index.js";
export {
  createAbilityProfileInputFromScoringResult,
  createBookRepositoryInputFromImportedBook,
  createCompletedChapterProgress,
  createDailyRecommendationsInputFromRecommendationResult,
  createProblemInputFromRecommendationProblem,
  createReadingProgressUpdateFromReaderState,
  mapProblemAttemptsToLearningEvents,
  mapProblemAttemptToLearningEvent,
  mapImportedBookSourceType,
  PrismaAgentPermissionRepository,
  PrismaAgentRuntimeRepository,
  PrismaAgentTaskRepository,
  PrismaBookRepository,
  PrismaChapterQaFeedbackRepository,
  PrismaChapterQaHistoryRepository,
  PrismaLearningRepository,
  PrismaProblemAttemptRepository,
  PrismaReadingProgressRepository,
  PrismaUserRepository,
  normalizeProgressRatio,
} from "./repositories/index.js";
export type {
  LlmCallPersistenceInput,
  LlmChatCompletionResultLike,
  MockLlmCallPersistenceBlockedReason,
  PersistMockLlmCallPreviewOptions,
  PersistMockLlmCallPreviewResult,
} from "./agent-llm-call-persistence.js";
export type {
  PersistRuntimeMockLlmCallInput,
  PersistRuntimeMockLlmCallOptions,
  PersistRuntimeMockLlmCallResult,
  RuntimeLlmCallExecutorLike,
  RuntimeLlmCallRequestLike,
  RuntimeLlmCallResultLike,
  RuntimeLlmCallSafeErrorSummaryLike,
  RuntimeLlmCallUsageLike,
  RuntimeMockLlmMetadataSummary,
  RuntimeMockLlmPersistenceMetadataSummary,
  RuntimeMockLlmPersistenceSafetyIssue,
  RuntimeMockLlmSafeErrorSummary,
  RuntimeMockLlmSafeErrorSummaryOptions,
} from "./runtime-mock-llm-call-persistence.js";
export type {
  ControlledSparkDiagnosticExecutorLike,
  ControlledSparkDiagnosticRequestLike,
  ControlledSparkDiagnosticResultLike,
  ControlledSparkDiagnosticStatus,
  ControlledSparkDiagnosticUsageLike,
  PersistRuntimeControlledSparkDiagnosticInput,
  PersistRuntimeControlledSparkDiagnosticOptions,
  PersistRuntimeControlledSparkDiagnosticResult,
  RuntimeControlledSparkDiagnosticMetadataSummary,
  RuntimeControlledSparkDiagnosticPersistenceMetadataSummary,
  RuntimeControlledSparkDiagnosticSafeErrorSummary,
  RuntimeControlledSparkDiagnosticSafeErrorSummaryOptions,
} from "./runtime-controlled-spark-diagnostic-persistence.js";
export type {
  PersistReadOnlyToolSandboxAuditPreviewOptions,
  PersistReadOnlyToolSandboxAuditPreviewResult,
  ReadOnlyToolSandboxExecutionResultLike,
  ReadOnlyToolSandboxPersistenceBlockedReason,
  ReadOnlyToolSandboxPersistenceInput,
} from "./agent-tool-sandbox-audit-persistence.js";
export type {
  PersistSparkDiagnosticPreviewOptions,
  PersistSparkDiagnosticPreviewResult,
  SparkControlledDiagnosticCallResultLike,
  SparkDiagnosticControlledStatus,
  SparkDiagnosticMetadataSummary,
  SparkDiagnosticPersistenceInput,
  SparkDiagnosticRuntimeLlmCallStatus,
  SparkDiagnosticSafeErrorSummary,
  SparkDiagnosticSafeErrorSummaryOptions,
} from "./spark-diagnostic-persistence.js";
export type {
  MockRuntimePersistenceCounts,
  MockRuntimePreviewPlanLike,
  PersistableMockRuntimePreviewInput,
  PersistMockRuntimePreviewOptions,
  PersistMockRuntimePreviewResult,
} from "./agent-runtime-mock-runner-preview.js";
export type {
  AgentPermissionDecisionPreviewLike,
  AgentPermissionRequestPreviewLike,
  AgentRuntimeAuditEventPreviewLike,
  AgentRuntimeErrorPreviewLike,
  AgentRuntimeEventPreviewLike,
  AgentRuntimeLlmCallPreviewLike,
  AgentRuntimePersistencePreviewInputs,
  AgentRuntimePreviewLike,
  AgentRuntimeStepPreviewLike,
  AgentRuntimeTokenEstimateLike,
  AgentRuntimeToolCallPreviewLike,
  AgentRuntimeTransitionResultLike,
  AgentTaskEventPreviewLike,
  AgentTaskExecutionReadinessPreviewLike,
  AgentTaskRecordPreviewLike,
  AgentTaskSnapshotPreviewLike,
  MapAgentPermissionDecisionPreviewOptions,
  MapAgentPermissionDecisionPreviewToCreateInputOptions,
  MapAgentPermissionRequestPreviewOptions,
  MapAgentPermissionRequestPreviewToCreateInputOptions,
} from "./mappers/index.js";
export type {
  AbilityProfileLike,
  AbilityScoringResultLike,
  AgentPermissionDecisionRecord,
  AgentPermissionRepository,
  AgentPermissionRepositoryJsonValue,
  AgentPermissionRequestRecord,
  AgentRuntimeAuditLogRecord,
  AgentRuntimeEventRecord,
  AgentRuntimeExecutionRecord,
  AgentRuntimeLlmCallRecord,
  AgentRuntimeRepository,
  AgentRuntimeRepositoryJsonValue,
  AgentRuntimeStepRecord,
  AgentRuntimeToolCallRecord,
  AgentTaskEventRecord,
  AgentTaskRecord,
  AgentTaskRepository,
  AgentTaskRepositoryJsonValue,
  AgentTaskSnapshotRecord,
  AgentTaskTimelineOrder,
  AppendAgentTaskEventInput,
  AppendAgentTaskSnapshotInput,
  AppendRuntimeAuditLogPreviewInput,
  AppendRuntimeEventPreviewInput,
  AppendRuntimeLlmCallPreviewInput,
  AppendRuntimeStepPreviewInput,
  AppendRuntimeToolCallPreviewInput,
  CreateAbilityProfileInputFromScoringResultInput,
  CreateAgentPermissionDecisionPreviewInput,
  CreateAgentPermissionRequestPreviewInput,
  CreateAgentTaskInput,
  CreateRuntimeExecutionPreviewInput,
  CreateCompletedChapterProgressInput,
  CreateDailyRecommendationsInputFromRecommendationResultInput,
  CreateProblemAttemptInput,
  CreateReadingProgressUpdateFromReaderStateInput,
  ImportedBookRepositoryChapter,
  ImportedBookRepositoryChunk,
  ImportedBookRepositoryDocument,
  ImportedBookRepositoryInput,
  ImportedBookRepositorySourceType,
  LearningMapperJsonObject,
  LearningMapperJsonPrimitive,
  LearningMapperJsonValue,
  LearningProblemDifficulty,
  LearningRecommendationStatus,
  ListAgentTaskTimelineOptions,
  ListAgentTasksByUserOptions,
  ListAgentPermissionDecisionsByRequestOptions,
  ListAgentPermissionDecisionsByTaskOptions,
  ListAgentPermissionRequestsByTaskOptions,
  ListRecentAgentPermissionRequestPreviewsOptions,
  ListRuntimeExecutionsByTaskOptions,
  ListRuntimeExecutionsByUserOptions,
  ListRuntimeRecordsByExecutionOptions,
  ListRecentPreviewTasksOptions,
  ListProblemAttemptsByUserOptions,
  ProblemAttemptCorrectnessInput,
  ProblemAttemptDifficultyInput,
  ProblemAttemptLearningDifficulty,
  ProblemAttemptLearningEvent,
  ProblemAttemptLearningEventJsonObject,
  ProblemAttemptLearningEventJsonPrimitive,
  ProblemAttemptLearningEventJsonValue,
  ProblemAttemptRecord,
  ProblemAttemptRepository,
  ProblemAttemptStatusInput,
  RecommendationProblemLike,
  RecommendationReasonLike,
  RecommendationResultLike,
  RecommendedProblemLike,
} from "./repositories/index.js";

export const dbPackage = "db";

export const dbPackageStatus: DbPackageStatus = "client-boundary";
