// Agent Runtime v1 -- Core Module Exports

// Pure type-only exports (interfaces, type aliases that have no const value counterpart)
export type {
  AgentId,
  AgentRole,
  AgentTask,
  AgentTaskFailure,
  AgentTaskInput,
  AgentExecutionState,
  AgentSharedContext,
  AgentPrivateContext,
  AgentToolCallSummary,
  AgentUsageSnapshot,
  AgentCancellationState,
  ConversationId,
  RunId,
  TaskId,
} from "./agent-types.ts";

// Value exports — their types are auto-exported alongside the values
export {
  AgentTaskStatus,
  AgentTaskPriority,
  AgentExecutionStatus,
  createInitialAgentExecutionState,
  transitionToRunning,
  transitionToCompleted,
  transitionToFailed,
  transitionToCancelled,
  addTask,
  startTask,
  completeTask,
  failTask,
  incrementTurn,
  setActiveAgent,
  updateSharedContext,
  updatePrivateAgentContext,
  recordToolCall,
  accumulateUsage,
} from "./agent-types.ts";

export type {
  AgentEvent,
  AgentEventBase,
  AgentEventId,
  AgentEventSequence,
  RunStartedEvent,
  RunCompletedEvent,
  RunFailedEvent,
  RunCancelledEvent,
  TaskCreatedEvent,
  TaskStartedEvent,
  TaskCompletedEvent,
  TaskFailedEvent,
  AgentStartedEvent,
  AgentProgressEvent,
  AgentCompletedEvent,
  AgentFailedEvent,
  ToolRequestedEvent,
  ToolStartedEvent,
  ToolCompletedEvent,
  ToolRejectedEvent,
  ToolFailedEvent,
  MemoryLoadedEvent,
  MemoryCompactedEvent,
  UsageUpdatedEvent,
  OutputDeltaEvent,
  OutputCompletedEvent,
} from "./agent-events.ts";

export {
  AgentEventType,
  resetEventSequence,
  createEventId,
  nextSequence,
  createRunStartedEvent,
  createRunCompletedEvent,
  createRunFailedEvent,
  createRunCancelledEvent,
  createTaskCreatedEvent,
  createTaskStartedEvent,
  createTaskCompletedEvent,
  createTaskFailedEvent,
  createAgentStartedEvent,
  createAgentCompletedEvent,
  createAgentFailedEvent,
  createToolRequestedEvent,
  createToolStartedEvent,
  createToolCompletedEvent,
  createToolRejectedEvent,
  createToolFailedEvent,
  createMemoryLoadedEvent,
  createMemoryCompactedEvent,
  createUsageUpdatedEvent,
  createOutputDeltaEvent,
  createOutputCompletedEvent,
} from "./agent-events.ts";
